AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.0
  Exclude:
    - bin/**/*
    - exe/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Layout:
  Metrics/LineLength:
    Max: 140

Style/Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Exclude:
    - spec/**/*.rb
